Repository dnd-side-project/dnd-8th-1-frontend, pull requests merged in 2023-04, with the labels that each got.

#320 📝 docs : README.md 작성하기
  README.md
  public/assets/images/Arch.png
  public/assets/images/example.png
Labels: type: 📝 docs, 우선순위 - 보통

#324 🚑 hotfix : 프로필 등록 하지 않은 유저가 플로팅 버튼 클릭 시 게시물 등록 페이지로 이동을 제한 하는 기능 추가
  src/pages/meet/index.tsx
  src/pages/performance/index.tsx
Labels: 🔥🔥🔥 핫픽스

#323 🚑 hotfix : 공연 정보 메인 페이지 내 배너 이미지 안 보이는 현상 및 텍스트 그라디언트 수정
  src/components/domain/performance/main/PerformanceBanner/index.tsx
Labels: 🔥🔥🔥 핫픽스

#327 🚑 hotfix : 활동 내역 페이지 내 후기 탭 empty UI 및 review 안 보이는 버그 핫 픽스
  src/components/domain/profile/history/MyReviewList/MyReviewItem.tsx
  src/components/domain/profile/history/MyReviewList/MyReviewList.stories.tsx
  src/components/domain/profile/history/MyReviewList/index.tsx
  src/dummy/profile/index.ts
  src/types/apis/model.ts
Labels: 🔥🔥🔥 핫픽스

#335 🚑 hotfix : MainPerformanceCommentList 컴포넌트 optional chaining 적용
  src/components/domain/main/MainPerformanceCommentList/index.tsx
Labels: 🔥🔥🔥 핫픽스

#341 ✨ feat: 로그인 필요한 페이지에 접근 제어 로직 추가
  src/pages/meet/edit/[meetId]/index.tsx
  src/pages/meet/edit/index.tsx
  src/pages/performance/edit/[performanceId]/index.tsx
  src/pages/performance/edit/index.tsx
  src/pages/profile/[profileId]/edit/index.tsx
  src/pages/profile/[profileId]/history/index.tsx
Labels: type: ✨ feature

#345 🐛 fix: 페이지 이동 후 필터 선택할 때, 페이지가 초기화되지 않는 오류 수정
  src/pages/meet/index.tsx
  src/pages/performance/index.tsx
Labels: type: 🐛 fix

#350 🔧 env: 스토리북 기본 코드 스니펫 설정
  .vscode/stories.tsx.code-snippets
Labels: type: 🔧 env

#347 ♻️ refactor : Calandar 컴포넌트 내 context 도입 및 useCalandar 문서화
  src/components/domain/performance/main/Calendar/CalendarSlider.tsx
  src/components/domain/performance/main/Calendar/CalendarSwiper.tsx
  src/components/domain/performance/main/Calendar/DayList.tsx
  src/components/domain/performance/main/Calendar/DayListItem.tsx
  src/components/domain/performance/main/Calendar/index.tsx
  src/hooks/useCalandar/index.ts
  src/pages/index.tsx
  src/pages/performance/index.tsx
  src/queries/performance/hooks/usePerformance.ts
Labels: type: ♻️ refactor

#343 ♻️ refactor: title 없는 페이지에 title 작성
  src/pages/_document.tsx
  src/pages/meet/[meetId]/candidate/index.tsx
  src/pages/meet/edit/[meetId]/index.tsx
  src/pages/meet/edit/index.tsx
  src/pages/performance/edit/[performanceId]/index.tsx
  src/pages/performance/edit/index.tsx
Labels: type: ♻️ refactor
