Repository dnd-side-project/dnd-8th-1-frontend, pull requests merged in 2023-02, with the labels that each got.

#21 ✨ feat : Label 컴포넌트 구현
  src/components/atoms/Label/Label.stories.tsx
  src/components/atoms/Label/index.tsx
  src/components/atoms/index.ts
Labels: 우선순위 - 보통, feat

#22 ✨ feat: Avatar 컴포넌트 구현
  .pnp.cjs
  .storybook/preview.js
  next.config.js
  package.json
  src/components/atoms/Avatar/Avatar.stories.tsx
  src/components/atoms/Avatar/index.tsx
  src/components/atoms/index.ts
  src/constants/image/index.ts
  src/constants/index.ts
  yarn.lock
Labels: 우선순위 - 보통, feat

#25 ✨ feat : Input 컴포넌트 구현
  src/components/atoms/Input/Input.stories.tsx
  src/components/atoms/Input/index.tsx
  src/components/atoms/index.ts
Labels: 우선순위 - 보통, feat

#28 ✨ feat : Dimmed 컴포넌트 구현
  src/components/atoms/Dimmed/Dimmed.stories.tsx
  src/components/atoms/Dimmed/index.tsx
  src/components/atoms/index.ts
Labels: 우선순위 - 보통, feat

#26 ✨ feat: Icon 컴포넌트 구현
  src/components/atoms/Icon/Icon.stories.tsx
  src/components/atoms/Icon/Iconset.ts
  src/components/atoms/Icon/index.tsx
Labels: 우선순위 - 보통, feat

#29 ✨ feat: StyledImage 컴포넌트 구현
  src/components/atoms/Avatar/index.tsx
  src/components/atoms/StyledImage/StyledImage.stories.tsx
  src/components/atoms/StyledImage/index.tsx
  src/components/atoms/index.ts
Labels: 우선순위 - 보통, feat

#32 ✨ feat : Textarea 컴포넌트 구현
  src/components/atoms/Textarea/Textarea.stories.tsx
  src/components/atoms/Textarea/index.tsx
  src/components/atoms/index.ts
Labels: 우선순위 - 보통, feat

#30 ✨ feat: Layout 컴포넌트 구현
  src/components/templates/Layout/Layout.stories.tsx
  src/components/templates/Layout/index.tsx
  src/components/templates/index.ts
Labels: 우선순위 - 보통, feat

#31 ✨ feat : Checkbox 컴포넌트 구현
  src/components/atoms/Checkbox/Checkbox.stories.tsx
  src/components/atoms/Checkbox/index.tsx
  src/components/atoms/index.ts
Labels: 우선순위 - 보통, feat

#41 ✨ feat: IconButton 컴포넌트 구현
  src/components/atoms/Icon/Iconset.ts
  src/components/atoms/Icon/index.tsx
  src/components/atoms/IconButton/IconButton.stories.tsx
  src/components/atoms/IconButton/index.tsx
  src/components/atoms/index.ts
  src/types/icon.ts
  src/types/index.ts
Labels: 우선순위 - 보통, feat

#39 ✨ feat: FormCategorySelect 구현
  src/components/molecules/FormCategorySelect/CategorySelect.stories.tsx
  src/components/molecules/FormCategorySelect/index.tsx
  src/components/molecules/index.ts
Labels: 우선순위 - 보통, feat

#42 ✨ feat : ToggleText 컴포넌트 구현
  src/components/molecules/ToggleText/ToggleText.stories.tsx
  src/components/molecules/ToggleText/index.tsx
  src/components/molecules/index.ts
  src/components/templates/StorybookForm/index.tsx
  src/components/templates/index.ts
Labels: 우선순위 - 보통, feat

#43 ✨ feat : StatusPopupContent 컴포넌트 구현
  src/components/molecules/StatusPopupContent/StatusPopupContent.stories.tsx
  src/components/molecules/StatusPopupContent/index.tsx
  src/components/molecules/index.ts
Labels: 우선순위 - 보통, feat

#45 ✨ feat : RegionButtonGroup 컴포넌트 구현
  src/components/molecules/RegionButtonGroup/RegionButtonGroup.stories.tsx
  src/components/molecules/RegionButtonGroup/index.tsx
  src/components/molecules/index.ts
  src/constants/index.ts
  src/constants/region/index.ts
Labels: 우선순위 - 보통, feat

#50 ✨ feat : Tags 컴포넌트 구현
  src/components/molecules/Tags/Tags.stories.tsx
  src/components/molecules/Tags/index.tsx
  src/types/genre.ts
  src/types/index.ts
  src/types/meet.ts
  src/types/region.ts
  src/types/type.ts
Labels: 우선순위 - 보통, feat

#44 ✨ feat : GenrePopupContent 컴포넌트 구현
  src/components/molecules/GenrePopupContent/GenrePopupContent.stories.tsx
  src/components/molecules/GenrePopupContent/index.tsx
  src/components/molecules/index.ts
  src/constants/genre/index.ts
  src/constants/index.ts
Labels: 우선순위 - 보통, feat

#51 📝 docs: 이슈 템플릿 스프린트 반영
  .github/issue_template.md
Labels: 문서화, 우선순위 - 급함

#56 ✨ feat : Header 컴포넌트 구현
  src/components/templates/Header/index.tsx
  src/components/templates/index.ts
Labels: 우선순위 - 보통, feat

#53 🤡 mock : msw 초기 세팅 진행
  package.json
  public/mockServiceWorker.js
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/mocks/server.ts
  src/pages/_app.tsx
Labels: 우선순위 - 보통, mock

#59 ✨ feat : 프로젝트에서 사용하는 아이콘들 추가
  src/components/atoms/Icon/Icon.stories.tsx
  src/components/atoms/Icon/Iconset.ts
  src/components/atoms/Icon/index.tsx
  src/components/atoms/IconButton/IconButton.stories.tsx
  src/components/molecules/GenrePopupContent/GenrePopupContent.stories.tsx
  src/components/molecules/Tags/Tags.stories.tsx
  src/components/molecules/Tags/index.tsx
  src/types/icon.ts
Labels: 우선순위 - 보통, feat

#57 💄 design: 스타일 관련 상수 정의
  src/constants/index.ts
  src/constants/styles/index.ts
  tailwind.config.js
Labels: 우선순위 - 급함

#63 🔧 env : 라우팅 구축 작업 진행
  src/pages/meet/[meetId]/candidate/index.tsx
  src/pages/meet/[meetId]/index.tsx
  src/pages/meet/edit/[meetId]/index.tsx
  src/pages/meet/edit/index.tsx
  src/pages/meet/index.tsx
  src/pages/oauth/callback/index.tsx
  src/pages/performance/[performanceId]/index.tsx
  src/pages/performance/edit/[performanceId]/index.tsx
  src/pages/performance/edit/index.tsx
  src/pages/performance/index.tsx
  src/pages/performance/search/index.tsx
  src/pages/profile/[profileId]/edit/index.tsx
  src/pages/profile/[profileId]/history/index.tsx
  src/pages/profile/[profileId]/index.tsx
  src/pages/profile/index.tsx
  src/pages/signup/index.tsx
Labels: env, 우선순위 - 급함

#67 ✨ feat : api 명세에 따른 타입(인터페이스) 정의
  src/types/apis/base.ts
  src/types/apis/index.ts
  src/types/apis/meet/index.ts
  src/types/apis/model.ts
  src/types/apis/performance/index.ts
  src/types/apis/user/index.ts
  src/types/genre/index.ts
  src/types/icons/index.ts
  src/types/index.ts
  src/types/meet/index.ts
  src/types/region/index.ts
Labels: 우선순위 - 낮음, type: ✨ feature

#76 ✨ feat: ImageWithDeadline 컴포넌트 구현
  .storybook/preview.js
  src/components/atoms/StyledImage/index.tsx
  src/components/molecules/ImageWithDeadline/ImageWithDeadline.stories.tsx
  src/components/molecules/ImageWithDeadline/index.tsx
  src/components/molecules/index.ts
  src/constants/date/index.ts
  src/constants/index.ts
  src/styles/globals.css
  src/utils/calculateDday/index.ts
  src/utils/index.ts
  src/utils/isDeadLine/index.tsx
Labels: 우선순위 - 보통

#74 ✨ feat: Tag 컴포넌트 구현
  src/components/atoms/Tag/Tags.stories.tsx
  src/components/atoms/Tag/index.tsx
  src/components/atoms/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#65 ✨ feat: SidebarMenu 컴포넌트 구현
  src/components/organisms/Header/index.tsx
  src/components/organisms/SidebarMenu/SidebarContent.tsx
  src/components/organisms/SidebarMenu/SidebarContentItem.tsx
  src/components/organisms/SidebarMenu/index.tsx
  src/components/organisms/index.ts
  src/components/templates/Header/index.tsx
  src/components/templates/Layout/index.tsx
  src/components/templates/index.ts
  src/hooks/index.ts
  src/hooks/useClickAway/index.ts
  src/hooks/useDelayUnmount/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: 우선순위 - 보통, type: ✨ feature

#80 ✨ feat : PerformanceBanner 컴포넌트 구현
  .pnp.cjs
  .yarn/cache/ssr-window-npm-4.0.2-01f9c0151e-df18260092.zip
  .yarn/cache/swiper-npm-9.0.5-afb755771d-33c45c0d9e.zip
  package.json
  src/components/organisms/PerformanceBanner/PerformanceBanner.stories.tsx
  src/components/organisms/PerformanceBanner/index.tsx
  src/components/organisms/index.ts
  src/styles/globals.css
  src/types/apis/index.ts
  yarn.lock
Labels: 우선순위 - 보통, type: ✨ feature

#72 ✨ feat : Calandar 컴포넌트 구현
  .pnp.cjs
  .yarn/cache/dayjs-npm-1.11.7-d5cd5b2919-5003a7c1dd.zip
  package.json
  src/components/organisms/Calandar/Calandar.stories.tsx
  src/components/organisms/Calandar/CalandarSlider.tsx
  src/components/organisms/Calandar/CalandarSwiper.tsx
  src/components/organisms/Calandar/DayList.tsx
  src/components/organisms/Calandar/DayListItem.tsx
  src/components/organisms/Calandar/index.tsx
  src/components/organisms/index.ts
  src/hooks/index.ts
  src/hooks/useCalandar/index.ts
  src/styles/globals.css
  yarn.lock
Labels: 우선순위 - 보통, type: ✨ feature

#82 ✨ feat: CollaboList 컴포넌트 구현
  src/components/atoms/Avatar/index.tsx
  src/components/atoms/Tag/index.tsx
  src/components/organisms/CollaboList/CollaboList.stories.tsx
  src/components/organisms/CollaboList/CollaboListItem.tsx
  src/components/organisms/CollaboList/index.tsx
  src/components/organisms/index.ts
  src/types/apis/meet/index.ts
  src/types/apis/model.ts
Labels: 우선순위 - 보통, type: ✨ feature

#87 ✨ feat: Pagination 컴포넌트 구현
  src/components/molecules/Pagination/Pagination.stories.tsx
  src/components/molecules/Pagination/index.tsx
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#90 ✨ feat: FilterButton 컴포넌트 구현
  src/components/molecules/FilterButton/FilterButton.stories.tsx
  src/components/molecules/FilterButton/index.tsx
  src/components/molecules/MeetPopupContent/MeetPopupContent.stories.tsx
  src/components/molecules/MeetPopupContent/index.tsx
  src/components/molecules/index.ts
  src/constants/index.ts
  src/constants/meet/index.tsx
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#88 ✨ feat: MeetBanner 컴포넌트 구현
  .storybook/main.js
  public/assets/images/meetBannarImage.png
  src/components/molecules/MeetBanner/MeetBanner.stories.tsx
  src/components/molecules/MeetBanner/index.tsx
  tailwind.config.js
  tsconfig.json
Labels: 우선순위 - 보통, type: ✨ feature

#92 ✨ feat : SearchHeader 컴포넌트 구현
  src/components/atoms/Dimmed/index.tsx
  src/components/atoms/Input/Input.stories.tsx
  src/components/organisms/SearchHeader/SearchHeader.stories.tsx
  src/components/organisms/SearchHeader/index.tsx
  src/components/organisms/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#85 ✨ feat : PerformanceList 컴포넌트 구현
  src/components/molecules/Tags/index.tsx
  src/components/organisms/PerformanceList/PerformanceList.stories.tsx
  src/components/organisms/PerformanceList/PerformanceListItem.tsx
  src/components/organisms/PerformanceList/index.tsx
  src/components/organisms/index.ts
  src/types/apis/model.ts
Labels: 우선순위 - 보통, type: ✨ feature

#93 ✨ feat: BottomSheet 컴포넌트 구현
  src/components/templates/BottomSheet/BottomSheet.stories.tsx
  src/components/templates/BottomSheet/index.tsx
  src/components/templates/Layout/index.tsx
  src/components/templates/index.ts
  src/hooks/index.ts
  src/hooks/useDisclosure/index.ts
  tailwind.config.js
Labels: 우선순위 - 보통

#96 💄 design: FilterButton 컴포넌트 레이아웃 이슈 해결
  src/components/molecules/FilterButton/index.tsx
Labels: 우선순위 - 보통

#98 ✨ feat: 만나기 메인 페이지 마크업
  public/assets/images/noneItemLogo.png
  src/components/molecules/index.ts
  src/components/organisms/CollaboList/index.tsx
  src/components/organisms/Header/index.tsx
  src/dummy/MeetPageDummy.ts
  src/dummy/index.ts
  src/pages/meet/index.tsx
  src/types/apis/index.ts
  src/types/apis/meet/index.ts
Labels: type: ✨ feature

#97 💄 design : filter 관련 컴포넌트 스타일링 수정
  src/components/molecules/FilterButton/index.tsx
  src/components/molecules/GenrePopupContent/GenrePopupContent.stories.tsx
  src/components/molecules/GenrePopupContent/index.tsx
  src/components/molecules/RegionButtonGroup/index.tsx
  src/components/molecules/RegionPopupContent/RegionPopupContent.stories.tsx
  src/components/molecules/RegionPopupContent/index.tsx
  src/components/molecules/StatusPopupContent/StatusPopupContent.stories.tsx
  src/components/molecules/StatusPopupContent/index.tsx
  src/components/molecules/index.ts
  src/constants/genre/index.ts
  src/types/apis/model.ts
Labels: 🔥 우선순위 - 급함, type: 💄 design

#99 ✨ feat: Modal 컴포넌트 구현
  src/components/templates/Modal/Modal.stories.tsx
  src/components/templates/Modal/index.tsx
Labels: 우선순위 - 보통, type: ✨ feature

#106 ✨ feat : PerformanceEntireList 컴포넌트 구현
  src/components/organisms/PerformanceEntireList/PerformanceEntireList.stories.tsx
  src/components/organisms/PerformanceEntireList/index.tsx
  src/components/organisms/PerformanceList/PerformanceListItem.tsx
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#116 ✨ feat : CandidateModal 컴포넌트 구현
  src/components/organisms/CandidateModal/CandidateModal.stories.tsx
  src/components/organisms/CandidateModal/index.tsx
  src/components/templates/Modal/index.tsx
  src/components/templates/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#120 ✨ feat : MeetDetailCard 컴포넌트 구현
  src/components/molecules/MeetDetailCard/MeetDetailCard.stories.tsx
  src/components/molecules/MeetDetailCard/index.tsx
  src/components/molecules/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#111 ✨ feat : MeetDetailImage 컴포넌트 구현
  src/components/molecules/MeetDetailImage/MeetDetailImage.stories.tsx
  src/components/molecules/MeetDetailImage/index.tsx
  src/components/molecules/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#103 ✨ feat: RegisterList 컴포넌트 구현
  .storybook/main.js
  src/components/organisms/CollaboList/CollaboList.stories.tsx
  src/components/organisms/RegisterList/RegisterList.stories.tsx
  src/components/organisms/RegisterList/RegisterListItem.tsx
  src/components/organisms/RegisterList/index.tsx
  src/dummy/MeetPageDummy.ts
  src/types/apis/meet/index.ts
  src/types/apis/model.ts
Labels: 우선순위 - 보통, type: ✨ feature

#117 ✨ feat: ImageUpload 컴포넌트 구현
  src/components/atoms/Icon/Iconset.ts
  src/components/atoms/ImageUpload/ImageUpload.stories.tsx
  src/components/atoms/ImageUpload/index.tsx
  src/components/atoms/index.ts
  src/types/apis/meet/index.ts
  src/types/icons/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#113 ✨ feat : CandidateBottomSheet 컴포넌트 구현
  src/components/atoms/Checkbox/index.tsx
  src/components/organisms/CandidateBottomSheet/CandidateBottomSheet.stories.tsx
  src/components/organisms/CandidateBottomSheet/index.tsx
  src/components/templates/BottomSheet/index.tsx
Labels: 우선순위 - 보통, type: ✨ feature

#133 ✨ feat: FormDatePicker 컴포넌트 구현
  .pnp.cjs
  .yarn/cache/@types-react-datepicker-npm-4.8.0-436ed0cec3-4404d6bd27.zip
  .yarn/cache/classnames-npm-2.3.2-d2fdae468d-2c62199789.zip
  .yarn/cache/date-fns-npm-2.29.3-fef7e3c72c-e01cf5b62a.zip
  .yarn/cache/react-datepicker-npm-4.10.0-9e447aacbd-d3e433e35a.zip
  .yarn/cache/react-onclickoutside-npm-6.12.2-61c80f0d9a-a0c7f4fbcf.zip
  .yarn/cache/react-popper-npm-2.3.0-1045578379-837111c987.zip
  .yarn/cache/warning-npm-4.0.3-291e921d6d-4f2cb6a957.zip
  package.json
  src/components/molecules/FormDatePicker/FormDatePicker.stories.tsx
  src/components/molecules/FormDatePicker/index.tsx
  src/components/molecules/index.ts
  src/constants/styles/index.ts
  yarn.lock
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#126 ✨ feat: RegionSelect 컴포넌트 구현
  src/components/molecules/RegionPopupContent/RegionPopupContent.stories.tsx
  src/components/molecules/RegionPopupContent/index.tsx
  src/components/molecules/RegionSelect/RegionSelect.stories.tsx
  src/components/molecules/RegionSelect/index.tsx
  src/components/molecules/index.ts
  src/components/organisms/CollaboList/index.tsx
Labels: 우선순위 - 보통, type: ✨ feature

#132 ✨ feat: CountPeople 컴포넌트 구현
  src/components/molecules/CountPeople/CountPeople.stories.tsx
  src/components/molecules/CountPeople/index.tsx
  src/components/molecules/index.ts
  src/types/meet/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#140 ✨ feat : CandidateCancelModal 컴포넌트 구현
  src/components/organisms/CandidateCancelModal/CandidateCancelModal.stories.tsx
  src/components/organisms/CandidateCancelModal/index.tsx
  src/components/organisms/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#143 ✨ feat: API 모듈화
  src/apis/common.ts
  src/apis/event/index.ts
  src/apis/index.ts
  src/types/apis/meet/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#146 🚑 hotfix: 인증이 필요한 API 의 config 를 읽지 못하는 에러 수정
  src/apis/common.ts
  src/apis/domains/event/index.ts
  src/apis/domains/index.ts
  src/apis/event/index.ts
  src/apis/index.ts
  src/apis/utils/authInstance.ts
  src/apis/utils/index.ts
  src/apis/utils/interceptors.ts
  src/apis/utils/unAuthInstance.ts
  tsconfig.json
Labels: 🔥 우선순위 - 급함, 🔥🔥🔥 핫픽스

#139 ✨ feat: 신청자 확인 페이지 마크업
  src/components/organisms/RegisterList/RegisterListItem.tsx
  src/components/organisms/RegisterList/index.tsx
  src/components/organisms/index.ts
  src/dummy/MeetCandidateDummy.ts
  src/pages/meet/[meetId]/candidate/index.tsx
  src/types/apis/model.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#142 ✨ feat : 공연 정보 상세 페이지 마크업
  src/components/atoms/Checkbox/index.tsx
  src/components/molecules/MeetDetailCard/MeetDetailCard.stories.tsx
  src/components/molecules/MeetDetailCard/index.tsx
  src/components/molecules/MeetDetailImage/index.tsx
  src/components/molecules/ToggleText/ToggleText.stories.tsx
  src/components/molecules/ToggleText/index.tsx
  src/components/molecules/index.ts
  src/components/organisms/CandidateBottomSheet/index.tsx
  src/components/organisms/CandidateCancelModal/index.tsx
  src/components/organisms/CandidateModal/index.tsx
  src/components/templates/BottomSheet/index.tsx
  src/components/templates/Layout/index.tsx
  src/components/templates/Modal/index.tsx
  src/dummy/index.ts
  src/dummy/meet/detail.ts
  src/pages/meet/[meetId]/index.tsx
  src/types/apis/model.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#141 ✨ feat: MeetCreateForm 컴포넌트 구현
  src/components/atoms/ImageUpload/index.tsx
  src/components/molecules/CountPeople/index.tsx
  src/components/molecules/FormCategorySelect/index.tsx
  src/components/molecules/FormDatePicker/index.tsx
  src/components/molecules/RegionSelect/index.tsx
  src/components/organisms/MeetCreateForm/index.tsx
  src/components/organisms/index.ts
  src/constants/meet/index.tsx
  src/types/apis/meet/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#148 ✨ feat: 글 수정 / 삭제 페이지 마크업
  src/components/organisms/FormHeader/index.tsx
  src/components/organisms/index.ts
  src/components/templates/Layout/index.tsx
  src/pages/meet/edit/[meetId]/index.tsx
  src/pages/meet/edit/index.tsx
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#149 ✨ feat : 만나기 전체 조회 api 연결
  next.config.js
  src/apis/domains/event/index.ts
  src/components/molecules/FilterButton/index.tsx
  src/components/organisms/CollaboList/index.tsx
  src/components/templates/Layout/index.tsx
  src/pages/_app.tsx
  src/pages/meet/index.tsx
  src/queries/index.ts
  src/queries/meet/useMeet.ts
  src/types/apis/base.ts
  tsconfig.json
Labels: 🔥 우선순위 - 급함, type: ✨ feature, 리뷰 보류

#152 ✨ feat : 만나기 상세 조회 api 연결
  src/components/molecules/MeetDetailCard/index.tsx
  src/pages/meet/[meetId]/index.tsx
  src/queries/meet/useMeetDetail.ts
  src/types/apis/meet/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#154 만나기 글 등록 기능 api 연결
  next.config.js
  src/apis/domains/event/index.ts
  src/components/organisms/MeetCreateForm/index.tsx
  src/constants/index.ts
  src/constants/queries/index.ts
  src/pages/meet/edit/index.tsx
  src/queries/index.ts
  src/queries/meet/useCreateImageUrl.ts
  src/queries/meet/useCreateMeet.ts
  src/queries/meet/useMeet.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#156 ✨ feat : 만나기 신청자 조회 api 연결
  src/apis/domains/event/index.ts
  src/components/organisms/RegisterList/index.tsx
  src/constants/queries/index.ts
  src/pages/meet/[meetId]/candidate/index.tsx
  src/queries/index.ts
  src/queries/meet/useCandidate.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#162 ✨ feat : 신청자 수락 기능 api 연결
  src/apis/domains/event/index.ts
  src/components/organisms/RegisterList/RegisterList.stories.tsx
  src/components/organisms/RegisterList/RegisterListItem.tsx
  src/dummy/MeetCandidateDummy.ts
  src/pages/meet/[meetId]/candidate/index.tsx
  src/queries/index.ts
  src/queries/meet/useAcceptCandidate.ts
  src/types/apis/model.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#163 ✨ feat : 만나기 조기마감 기능 api 연결
  src/apis/domains/event/index.ts
  src/pages/meet/[meetId]/candidate/index.tsx
  src/queries/index.ts
  src/queries/meet/useMeetDeadline.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#164 ✨ feat : 만나기 신청 기능 api 연결
  src/apis/domains/event/index.ts
  src/pages/meet/[meetId]/index.tsx
  src/queries/index.ts
  src/queries/meet/useRequestCandidate.ts
  src/types/apis/meet/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#165 ✨ feat : 만나기 신청 취소 기능 api 연결
  src/pages/meet/[meetId]/index.tsx
  src/queries/index.ts
  src/queries/meet/useCancelCandidate.ts
  src/queries/meet/useRequestCandidate.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#166 ✨ feat : 만나기 수정 기능 api 연결
  src/apis/domains/event/index.ts
  src/components/organisms/MeetCreateForm/index.tsx
  src/dummy/index.ts
  src/dummy/meet/modify.ts
  src/pages/meet/edit/[meetId]/index.tsx
  src/queries/index.ts
  src/queries/meet/useModifyMeet.ts
  src/types/apis/meet/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#168 ✨ feat : 만나기 삭제 기능 api 연결
  src/apis/domains/event/index.ts
  src/components/organisms/MeetDeleteModal/index.tsx
  src/pages/meet/[meetId]/index.tsx
  src/queries/index.ts
  src/queries/meet/useDeleteMeet.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#175 💄 design : 디자이너 요구사항 반영
  src/components/molecules/FormDatePicker/index.tsx
  src/components/organisms/SidebarMenu/SidebarContent.tsx
  src/components/organisms/SidebarMenu/index.tsx
  src/utils/date/calculateDday.ts
  src/utils/date/index.ts
  src/utils/date/isDeadLine.ts
  src/utils/date/isPossibleDay.ts
  src/utils/index.ts
Labels: type: 💄 design

#176 🍱 asset: asset 파일 추가
  public/assets/images/Background_dancer.png
  public/assets/images/Background_team.png
  public/assets/images/collabo_share_main.png
  public/assets/images/danverce.png
  public/assets/images/graphic_1.png
  public/assets/images/graphic_2.png
  public/assets/images/meetBannarImage.png
  public/assets/images/noneItemLogo.png
  public/assets/logo/logo_big.png
  public/assets/logo/logo_small.png
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  src/components/molecules/MeetBanner/index.tsx
  src/components/organisms/CollaboList/index.tsx
  src/components/organisms/RegisterList/index.tsx
Labels: 우선순위 - 보통, type: 🍱 asset

#182 ✨ feat : SearchResultHeader 컴포넌트 구현
  .storybook/main.js
  .storybook/preview.js
  src/components/SearchResultHeader/SearchResultHeader.stories.tsx
  src/components/SearchResultHeader/index.tsx
  src/components/organisms/MeetCreateForm/index.tsx
  src/dummy/performance/detail.ts
  src/queries/index.ts
  src/utils/storybookMock/router.js
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#190 ✨ feat: Header 에 로고 추가
  src/components/organisms/Header/index.tsx
Labels: type: ✨ feature

#185 ✨ feat : SearchResultList 컴포넌트 구현
  .storybook/main.js
  src/components/organisms/SearchResultHeader/SearchResultHeader.stories.tsx
  src/components/organisms/SearchResultHeader/index.tsx
  src/components/organisms/SearchResultList/SearchResultList.stories.tsx
  src/components/organisms/SearchResultList/SearchResultListItem.tsx
  src/components/organisms/SearchResultList/index.tsx
  src/components/organisms/index.ts
  src/types/apis/model.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#186 ✨ feat : SearchResultTab 컴포넌트 구현
  src/components/molecules/SearchResultTab/SearchResultTab.stories.tsx
  src/components/molecules/SearchResultTab/index.tsx
  src/components/molecules/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#174 🐛 fix : 만나기 기능 api 연결한 로직들 수정 작업
  src/components/atoms/Dimmed/index.tsx
  src/components/organisms/MeetCreateForm/index.tsx
  src/pages/meet/[meetId]/index.tsx
  src/pages/meet/index.tsx
  src/queries/meet/useMeet.ts
  src/queries/meet/useRequestCandidate.ts
Labels: 우선순위 - 보통, type: 🐛 fix

#191 ✨ feat : GenreSelect 컴포넌트 구현
  src/components/molecules/GenreSelect/GenreSelect.stories.tsx
  src/components/molecules/GenreSelect/GenreSelectPopupContent.tsx
  src/components/molecules/GenreSelect/index.tsx
  src/components/molecules/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#203 ✨ feat: ProfileLinkButton 컴포넌트 구현
  src/components/molecules/ProfileLinkButton/ProfileLinkButton.stories.tsx
  src/components/molecules/ProfileLinkButton/index.tsx
  src/components/molecules/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#204 ✨ feat: PerformanceReviewList 컴포넌트 구현
  src/components/organisms/PerformanceReviewList/PerformanceReviewItem.tsx
  src/components/organisms/PerformanceReviewList/PerformanceReviewList.stories.tsx
  src/components/organisms/PerformanceReviewList/index.tsx
  src/components/organisms/RegisterList/RegisterList.stories.tsx
  src/components/organisms/index.ts
  src/types/apis/model.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#197 ✨ feat: Spacer 컴포넌트 구현
  src/components/atoms/Spacer/Spacer.stories.tsx
  src/components/atoms/Spacer/index.tsx
  src/components/atoms/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#199 ✨ feat : PerformanceInfo 컴포넌트 구현
  src/components/organisms/PerformanceInfo/PerformanceInfo.stories.tsx
  src/components/organisms/PerformanceInfo/index.tsx
  src/components/organisms/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#193 ✨ feat: PerformanceDetailSectionTop 컴포넌트 구현
  src/components/organisms/PerformanceDetailSectionTop/index.tsx
  src/components/organisms/index.ts
  src/components/templates/CancelSubmitModal/index.tsx
  src/components/templates/Modal/index.tsx
  src/pages/performance/[performanceId]/index.tsx
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#180 📝 docs : useQuery, useMutation hook 관련 문서화
  src/@hook/index.md
Labels: type: 📝 docs, 우선순위 - 보통

#195 ✨ feat : ConfirmModal 컴포넌트 구현
  src/components/templates/ConfirmModal/ConfirmModal.stories.tsx
  src/components/templates/ConfirmModal/index.tsx
  src/components/templates/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#210 ✨ feat : 공연 정보 메인 페이지 마크업
  src/components/organisms/Calandar/Calandar.stories.tsx
  src/components/organisms/Calandar/CalandarSlider.tsx
  src/components/organisms/Calandar/CalandarSwiper.tsx
  src/components/organisms/Calandar/DayList.tsx
  src/components/organisms/Calandar/DayListItem.tsx
  src/components/organisms/Calandar/index.tsx
  src/components/organisms/PerformanceBanner/index.tsx
  src/components/organisms/SearchHeader/index.tsx
  src/dummy/index.ts
  src/dummy/performance/index.ts
  src/pages/_app.tsx
  src/pages/performance/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  src/styles/swiper.css
  src/types/apis/model.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#209 ✨ feat : 공연 정보 검색 페이지 마크업
  src/components/molecules/SearchResultImage/index.tsx
  src/components/molecules/SearchResultTab/index.tsx
  src/components/molecules/index.ts
  src/components/organisms/Header/index.tsx
  src/components/organisms/SearchResultHeader/index.tsx
  src/components/organisms/SearchResultList/SearchResultListItem.tsx
  src/components/organisms/SearchResultList/index.tsx
  src/components/organisms/index.ts
  src/components/templates/Layout/index.tsx
  src/dummy/index.ts
  src/dummy/performance/search.ts
  src/pages/performance/search/index.tsx
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#206 ✨ feat: 공연 상세 정보 페이지 마크업
  src/components/atoms/Tag/index.tsx
  src/components/molecules/ProfileLinkButton/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/PerformanceReviewList/PerformanceReviewItem.tsx
  src/components/organisms/PerformanceReviewSection/PerformanceReviewSection.stories.tsx
  src/components/organisms/PerformanceReviewSection/index.tsx
  src/components/organisms/PerformanceReviewTextArea/index.tsx
  src/components/organisms/PerformanceSectionMiddle/index.tsx
  src/components/organisms/index.ts
  src/pages/performance/[performanceId]/index.tsx
Labels: 우선순위 - 보통, type: ✨ feature

#217 ✨ feat: 공연 상세 조회 서버 통신 구현
  src/apis/domains/performance/index.ts
  src/components/molecules/ProfileLinkButton/index.tsx
  src/components/organisms/PerformanceReviewList/index.tsx
  src/constants/queries/index.ts
  src/pages/_app.tsx
  src/pages/performance/[performanceId]/index.tsx
  src/queries/index.ts
  src/queries/performance/hooks/index.ts
  src/queries/performance/hooks/useCreateReview.ts
  src/queries/performance/hooks/useDeletePerformance.ts
  src/queries/performance/hooks/useDetailPerformance.ts
  src/queries/performance/hooks/useGetReviews.ts
  src/queries/performance/index.ts
  src/queries/performance/performanceKeys.ts
  src/types/apis/model.ts
  src/types/apis/performance/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#218 ✨ feat : 공연 정보 메인 페이지 api 연결
  src/apis/domains/performance/index.ts
  src/components/molecules/FilterButton/index.tsx
  src/components/molecules/GenrePopupContent/index.tsx
  src/components/molecules/Pagination/index.tsx
  src/components/organisms/Calandar/CalandarSlider.tsx
  src/components/organisms/Calendar/Calendar.stories.tsx
  src/components/organisms/Calendar/CalendarSlider.tsx
  src/components/organisms/Calendar/CalendarSwiper.tsx
  src/components/organisms/Calendar/DayList.tsx
  src/components/organisms/Calendar/DayListItem.tsx
  src/components/organisms/Calendar/index.tsx
  src/components/organisms/PerformanceBanner/index.tsx
  src/components/organisms/PerformanceEntireList/PerformanceEntireList.stories.tsx
  src/components/organisms/PerformanceEntireList/index.tsx
  src/components/organisms/PerformanceList/PerformanceList.stories.tsx
  src/components/organisms/PerformanceList/PerformanceListItem.tsx
  src/components/organisms/PerformanceList/index.tsx
  src/components/organisms/index.ts
  src/constants/date/index.ts
  src/constants/queries/index.ts
  src/pages/performance/index.tsx
  src/queries/meet/useAcceptCandidate.ts
  src/queries/meet/useCancelCandidate.ts
  src/queries/meet/useCandidate.ts
  src/queries/meet/useCreateMeet.ts
  src/queries/meet/useDeleteMeet.ts
  src/queries/meet/useMeet.ts
  src/queries/meet/useMeetDeadline.ts
  src/queries/meet/useMeetDetail.ts
  src/queries/meet/useModifyMeet.ts
  src/queries/meet/useRequestCandidate.ts
  src/queries/performance/index.ts
  src/queries/performance/useImminentPerformance.ts
  src/queries/performance/usePerformance.ts
  src/types/apis/model.ts
  src/types/apis/performance/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#242 ✨ feat : MainPerformanceSection 컴포넌트 구현
  public/assets/images/main_location.png
  src/components/organisms/MainPerformanceSection/MainPerformanceCommentList.tsx
  src/components/organisms/MainPerformanceSection/MainPerformanceCommentListItem.tsx
  src/components/organisms/MainPerformanceSection/MainPerformanceList.tsx
  src/components/organisms/MainPerformanceSection/MainPerformanceListItem.tsx
  src/components/organisms/MainPerformanceSection/MainPerformanceSection.stories.tsx
  src/components/organisms/MainPerformanceSection/index.tsx
  src/components/organisms/index.ts
  src/types/apis/model.ts
  tailwind.config.js
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#239 ✨ feat : MainMeetSection 컴포넌트 구현
  src/components/organisms/MainMeetSection/MainMeetList.tsx
  src/components/organisms/MainMeetSection/MainMeetListItem.tsx
  src/components/organisms/MainMeetSection/MainMeetSection.stories.tsx
  src/components/organisms/MainMeetSection/index.tsx
  src/components/organisms/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#236 ✨ feat : MainBanner 컴포넌트 구현
  public/assets/images/main_banner_blue.png
  public/assets/images/main_banner_green.png
  public/assets/images/main_banner_purple.png
  src/components/organisms/MainBanner/MainBanner.stories.tsx
  src/components/organisms/MainBanner/index.tsx
Labels: 우선순위 - 보통, type: ✨ feature

#228 ✨ feat: MainProfileSection 컴포넌트 구현
  src/components/organisms/MainPerformanceSection/MainPerformanceList.tsx
  src/components/organisms/MainPerformanceSection/MainPerformanceListItem.tsx
  src/components/organisms/MainPerformanceSection/MainPerformanceSection.stories.tsx
  src/components/organisms/MainProfileList/MainProfileItem.tsx
  src/components/organisms/MainProfileList/MainProfileList.stories.tsx
  src/components/organisms/MainProfileList/index.tsx
  src/components/organisms/MainProfileSection/MainProfileSection.stories.tsx
  src/components/organisms/MainProfileSection/index.tsx
  src/components/organisms/index.ts
  src/types/apis/index.ts
  src/types/apis/model.ts
  src/types/apis/profile/index.ts
Labels: type: ✨ feature

#234 ✨ feat: profileHistoryTab 컴포넌트 구현
  src/components/molecules/ProfileHistoryTab/ProfileHistoryTab.stories.tsx
  src/components/molecules/ProfileHistoryTab/index.tsx
  src/components/molecules/index.ts
  src/types/index.ts
  src/types/profile/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#235 ✨ feat : 공연 정보 수정 페이지 마크업 & api 연결
  src/apis/domains/performance/index.ts
  src/components/molecules/FormDatePicker/FormDateTimePicker.tsx
  src/components/organisms/PerformanceCreateForm/index.tsx
  src/components/organisms/index.ts
  src/pages/performance/edit/[performanceId]/index.tsx
  src/queries/performance/hooks/index.ts
  src/queries/performance/hooks/useModifyPerformance.ts
Labels: 우선순위 - 보통, type: ✨ feature

#246 ✨ feat: ProfileSubCategoryTab 컴포넌트 구현
  src/components/molecules/ProfileSubCategoryTab/ProfileSubCategoryTab.stories.tsx
  src/components/molecules/ProfileSubCategoryTab/index.tsx
  src/components/molecules/index.ts
  src/components/organisms/ActivityCategorySelector/ActivityCategorySelector.stories.tsx
  src/components/organisms/ActivityCategorySelector/index.tsx
  src/components/organisms/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#244 ✨ feat: MyEventList 컴포넌트 구현
  src/components/atoms/StyledImage/index.tsx
  src/components/molecules/ActivityEmptyHelper/index.tsx
  src/components/molecules/index.ts
  src/components/organisms/MyEventList/MyEventItem.tsx
  src/components/organisms/MyEventList/MyEventList.stories.tsx
  src/components/organisms/MyEventList/index.tsx
  src/components/organisms/index.ts
  src/constants/styles/index.ts
  src/types/apis/model.ts
  src/types/apis/profile/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#229 ✨ feat: ProfileDatePicker 컴포넌트 구현
  src/components/molecules/ProfileDatePicker/index.tsx
  src/components/molecules/index.ts
  src/pages/_app.tsx
  src/styles/datepicker.css
Labels: 우선순위 - 보통, type: ✨ feature

#250 ✨ feat : 메인 페이지 마크업 & api 연결
  src/apis/domains/index.ts
  src/apis/domains/main/index.ts
  src/apis/domains/performance/index.ts
  src/components/organisms/Header/index.tsx
  src/components/organisms/MainMeetSection/MainMeetList.tsx
  src/components/organisms/MainMeetSection/MainMeetListItem.tsx
  src/components/organisms/MainMeetSection/index.tsx
  src/components/organisms/MainPerformanceSection/MainPerformanceList.tsx
  src/components/organisms/MainPerformanceSection/MainPerformanceListItem.tsx
  src/components/organisms/MainPerformanceSection/index.tsx
  src/components/organisms/MainProfileList/index.tsx
  src/components/organisms/PerformanceReviewList/PerformanceReviewItem.tsx
  src/components/organisms/index.ts
  src/pages/index.tsx
  src/queries/index.ts
  src/queries/main/hooks/index.ts
  src/queries/main/hooks/useLastestReviews.ts
  src/queries/main/hooks/useProfile.ts
  src/queries/main/index.ts
  src/queries/main/mainKeys.ts
  src/queries/meet/useMeet.ts
  src/queries/performance/index.ts
  src/queries/performance/usePerformance.ts
  src/types/apis/index.ts
  src/types/apis/main/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#256 ✨ feat: MyReviewList 컴포넌트 구현
  .pnp.cjs
  .yarn/cache/@tailwindcss-line-clamp-npm-0.4.2-7e8725ef00-26b8135df2.zip
  package.json
  src/components/organisms/MyReviewList/MyReviewItem.tsx
  src/components/organisms/MyReviewList/MyReviewList.stories.tsx
  src/components/organisms/MyReviewList/index.tsx
  src/types/apis/model.ts
  src/types/apis/profile/index.ts
  tailwind.config.js
  yarn.lock
Labels: 우선순위 - 보통, type: ✨ feature

#252 ✨ feat: ProfileTopSection 컴포넌트 구현
  src/components/molecules/ProfileBackgroundSection/ProfileBackgroundSection.stories.tsx
  src/components/molecules/ProfileBackgroundSection/index.tsx
  src/components/molecules/ProfileInfo/ProfileInfo.stories.tsx
  src/components/molecules/ProfileInfo/index.tsx
  src/components/molecules/index.ts
  src/components/organisms/ProfileTopSection/ProfileTopSection.stories.tsx
  src/components/organisms/ProfileTopSection/index.tsx
  src/components/organisms/index.ts
  src/constants/styles/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#262 ✨ feat: ProfileDisabled 컴포넌트 구현
  public/assets/images/Background_black.png
  src/components/organisms/ProfileDisabled/ProfileDisabled.stories.tsx
  src/components/organisms/ProfileDisabled/index.tsx
Labels: type: ✨ feature

#259 ✨ feat: ProfileDescription 컴포넌트 구현
  src/components/molecules/ProfileDescription/ProfileDescription.stories.tsx
  src/components/molecules/ProfileDescription/index.tsx
  src/components/molecules/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#255 ✨ feat: MyPerformanceList 컴포넌트 구현
  src/components/organisms/MyPerformanceList/MyPerformanceItem.tsx
  src/components/organisms/MyPerformanceList/MyPerformanceList.stories.tsx
  src/components/organisms/MyPerformanceList/index.tsx
  src/types/apis/model.ts
  src/types/apis/profile/index.ts
Labels: type: ✨ feature

#265 ✨ feat : AdditionalInfoPopup 컴포넌트 구현
  src/components/organisms/FormTitleHeader/index.tsx
  src/components/organisms/index.ts
  src/components/templates/AdditionalInfoPopup/index.tsx
  src/components/templates/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#261 ✨ feat: PortfolioLinkModal 컴포넌트 구현
  src/components/organisms/PortfolioLinkModal/index.tsx
  src/components/organisms/index.ts
  src/types/apis/model.ts
Labels: 우선순위 - 보통, type: ✨ feature

#268 ✨ feat : OpenchatPopup 컴포넌트 구현
  src/components/organisms/OpenchatPopup/index.tsx
  src/components/organisms/index.ts
  src/constants/index.ts
  src/constants/validation/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#270 ✨ feat: CheckboxModal 컴포넌트 구현
  src/components/templates/CheckboxModal/index.tsx
  src/components/templates/index.ts
  src/constants/styles/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#272 ✨ feat: MyProfileMenu 컴포넌트 구현
  src/components/organisms/MyProfileMenu/MyProfileMenu.stories.tsx
  src/components/organisms/MyProfileMenu/MyProfileMenuItem.tsx
  src/components/organisms/MyProfileMenu/index.tsx
Labels: 우선순위 - 보통, type: ✨ feature

#271 ✨ feat: ProfileButtonGroup 구현
  src/components/atoms/Icon/Iconset.ts
  src/components/organisms/ProfileButtonGroup/OpenChatButton.tsx
  src/components/organisms/ProfileButtonGroup/PortfolioButton.tsx
  src/components/organisms/ProfileButtonGroup/ProfileButtonGroup.stories.tsx
  src/components/organisms/ProfileButtonGroup/index.tsx
  src/components/organisms/index.ts
  src/constants/styles/index.ts
  src/types/apis/model.ts
  src/types/icons/index.ts
Labels: 🔥 우선순위 - 급함, type: ✨ feature

#277 ✨ feat : ProfileImgUpload 컴포넌트 구현
  src/components/molecules/ProfileImgUpload/ProfileImgUpload.stories.tsx
  src/components/molecules/ProfileImgUpload/index.tsx
  src/components/molecules/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#275 ✨ feat : PortfolioPopup 컴포넌트 구현
  src/components/organisms/PortfolioPopup/index.tsx
  src/components/organisms/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#274 ✨ feat: ModalWithSingleButton 컴포넌트 구현
  src/components/organisms/ProfileRegisterContent/ProfileRegisterContent.stories.tsx
  src/components/organisms/ProfileRegisterContent/index.tsx
  src/components/organisms/WelcomeModalContent/WelcomeModalContent.stories.tsx
  src/components/organisms/WelcomeModalContent/index.tsx
  src/components/organisms/index.ts
  src/components/templates/Modal/index.tsx
  src/components/templates/ModalWithSingleButton/ModalWithSingleButton.stories.tsx
  src/components/templates/ModalWithSingleButton/index.tsx
  src/constants/styles/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#284 ✨ feat: 프로필 페이지 마크업
  src/components/molecules/ProfileInfo/index.tsx
  src/components/organisms/MyProfileMenu/MyProfileMenuItem.tsx
  src/components/organisms/MyProfileMenu/index.tsx
  src/components/organisms/ProfileButtonGroup/index.tsx
  src/components/organisms/ProfileDisabled/index.tsx
  src/components/organisms/ProfileTopSection/index.tsx
  src/components/organisms/index.ts
  src/components/templates/Modal/index.tsx
  src/pages/profile/[profileId]/index.tsx
  src/utils/checkField/index.ts
  src/utils/index.ts
Labels: 우선순위 - 보통, type: ✨ feature

#280 ✨ feat: 로그인 페이지 마크업
  public/assets/logo/g-logo.png
  src/components/molecules/GoogleLoginButton/index.tsx
  src/components/molecules/index.ts
  src/components/organisms/Header/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  tailwind.config.js
Labels: type: ✨ feature

#283 ✨ feat: 활동내역 페이지 마크업
  src/components/molecules/ProfileHistoryTab/index.tsx
  src/components/organisms/ActivityCategorySelector/index.tsx
  src/components/organisms/MyAppliedEventList/MyAppliedEventItem.tsx
  src/components/organisms/MyEventList/MyEventItem.tsx
  src/components/organisms/MyPerformanceList/MyPerformanceItem.tsx
  src/components/organisms/index.ts
  src/constants/index.ts
  src/constants/profile/index.tsx
  src/dummy/index.ts
  src/dummy/profile/index.ts
  src/pages/profile/[profileId]/history/index.tsx
Labels: 우선순위 - 보통, type: ✨ feature
